spring:
  main:
    allow-circular-references: 'true'
  application:
    name: eureka_usermanagement_client
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/usertest
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
    com:
      usermanagement: DEBUG
  file: C:\Users\syedasal\Documents\Capillary-Trainings\usermanagement.log
jwt:
  secret: javainuse
eureka:
  client:
    instance:
      preferIpAddress: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
